### ISSUE TITLE
What is the orignals folder?

### ISSUE THREAD

**Issue by lfrcoder** [srp-31/Object-Detection-Data-Augmentation#2]
hi，
Thank you for your code
I have a question here.
What is the difference between the orignals folder and bkg.jpg in the background folder?

**Comment by srp-31** [comment]
Hello,

Thank you for the interest. Its still work in progress and thats ewhy I havent documented it too well.

The orginals contain the original files downloaded from the internet. The other backgorund files I created by resizing them so that the sample images are smaller than the background images and hence they can placed at different positions on thebackground. Hope it is clear now.
