### ISSUE TITLE
Data Augmentation in multi-class labeled dataset

### ISSUE THREAD

**Issue by amit2319** [srp-31/Object-Detection-Data-Augmentation#6]
I already have a multi-class labeled dataset. 
How can I use this library to augment and generate a larger dataset, and preserve labeling(bounding boxes)?

**Comment by srp-31** [comment]
Hi

Sorry fo the super late reply. I was busy with some other task.
This tool was meant to help when you have seperate cropped images of the object to be detected which is to be added to some background images so that there is a dataset where the object is 'present in the wild'. This dataset could be used to train an object detector. This whoel tool was written keeping in mind the data geenration performed by OpenCV for Haar Face detector. Although I have written it for one object class , I am sure modifying it for multiple classes wont be too difficult. Do let me know if any part of the code is not clear. I am closing the issue as of now.
